#!/usr/bin/env -S tsx
/**
 * Phase-2 R7: regenerate the autogen reference section in
 * `docs/hcs20-v2-schema.md` from the canonical Zod schemas in
 * `src/custodial/hcs20-schema.ts`.
 *
 * Pre-fix the doc was hand-maintained and drifted from the writer
 * (R6-FG-59..62). The schema is now the source of truth — this
 * script walks `HCS20_SCHEMAS` and emits a markdown table of every
 * field with its description, type, and required/optional status.
 *
 * The script ONLY replaces content between the marker comments
 * `<!-- AUTOGEN-SCHEMA-START -->` and `<!-- AUTOGEN-SCHEMA-END -->`.
 * Hand-curated prose above and below is preserved.
 *
 * Usage:
 *   npm run schema:docs           — write to docs/hcs20-v2-schema.md
 *   npm run schema:docs -- --check — exit 1 if the file would change
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { HCS20_SCHEMAS, type Hcs20OpName } from '../custodial/hcs20-schema.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const DOC_PATH = join(REPO_ROOT, 'docs', 'hcs20-v2-schema.md');
const START_MARKER = '<!-- AUTOGEN-SCHEMA-START -->';
const END_MARKER = '<!-- AUTOGEN-SCHEMA-END -->';

interface FieldRow {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

/**
 * Render a single Zod schema's field table by walking its JSON Schema
 * representation. Forward-compatible with new field types — a field
 * that toJSONSchema can't express still appears in the table with
 * `type: "(see schema)"`.
 */
function tableForSchema(opName: Hcs20OpName, schema: z.ZodType): string {
  const json = z.toJSONSchema(schema, { unrepresentable: 'any' }) as Record<
    string,
    unknown
  > & {
    description?: string;
    properties?: Record<string, Record<string, unknown> & { description?: string }>;
    required?: string[];
  };
  const description = (json.description as string | undefined) ?? '';
  const props = json.properties ?? {};
  const required = new Set(json.required ?? []);

  const rows: FieldRow[] = [];
  for (const [fieldName, fieldSchema] of Object.entries(props)) {
    rows.push({
      name: fieldName,
      type: describeType(fieldSchema as Record<string, unknown>),
      required: required.has(fieldName),
      description: ((fieldSchema as { description?: string }).description ?? '').replace(
        /\s+/g,
        ' ',
      ).trim(),
    });
  }

  const header = `### \`op: "${opName}"\`\n\n${description}\n`;
  if (rows.length === 0) {
    return `${header}\n_(schema has no fields)_\n`;
  }
  const tableHeader =
    '| Field | Type | Required | Description |\n' +
    '|---|---|---|---|';
  const tableBody = rows
    .map(
      (r) =>
        `| \`${r.name}\` | ${r.type} | ${r.required ? 'yes' : 'no'} | ${escapeCell(r.description) || '—'} |`,
    )
    .join('\n');
  return `${header}\n${tableHeader}\n${tableBody}\n`;
}

function describeType(fieldJson: Record<string, unknown>): string {
  if ('const' in fieldJson) {
    return `\`${JSON.stringify(fieldJson.const)}\` (literal)`;
  }
  if ('enum' in fieldJson && Array.isArray(fieldJson.enum)) {
    const values = fieldJson.enum as unknown[];
    if (values.length <= 6) {
      return values.map((v) => `\`${JSON.stringify(v)}\``).join(' \\| ');
    }
    return `enum (${values.length} values)`;
  }
  if ('anyOf' in fieldJson && Array.isArray(fieldJson.anyOf)) {
    return (fieldJson.anyOf as Record<string, unknown>[])
      .map(describeType)
      .join(' \\| ');
  }
  if ('oneOf' in fieldJson && Array.isArray(fieldJson.oneOf)) {
    // R8-FG-31 / Phase-6 Cluster A: recurse like anyOf does. Pre-fix
    // this collapsed every oneOf to the literal string
    // "discriminated union" — silently drops information from the
    // schema, which IS the source of truth in Phase 2.
    return (fieldJson.oneOf as Record<string, unknown>[])
      .map(describeType)
      .join(' \\| ');
  }
  if ('type' in fieldJson) {
    const type = fieldJson.type as string | string[];
    if (Array.isArray(type)) return type.join(' \\| ');
    if (type === 'array') {
      const items = fieldJson.items as Record<string, unknown> | undefined;
      return `array of ${items ? describeType(items) : 'any'}`;
    }
    if (type === 'object') return 'object';
    return type;
  }
  return '(see schema)';
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function generateAutogen(): string {
  const sections: string[] = [];
  sections.push(
    `<!-- This section is autogenerated by \`npm run schema:docs\`. -->\n` +
      `<!-- DO NOT EDIT BY HAND. -->\n` +
      `<!-- Source: src/custodial/hcs20-schema.ts -->\n`,
  );
  sections.push(`## Schema reference (autogenerated)\n`);
  sections.push(
    `> Generated from the canonical Zod schemas. The writer parses\n> outbound payloads against these schemas before submission, so a\n> field present here is the contract clients can rely on.\n`,
  );

  const opOrder: Hcs20OpName[] = [
    // v2 first
    'play_session_open',
    'play_pool_result',
    'play_session_close',
    'play_session_aborted',
    'refund',
    'prize_recovery',
    'strategy_change',
    // v1 + control
    'mint',
    'transfer',
    'burn',
    'batch',
    'deploy',
    'control',
  ];

  for (const op of opOrder) {
    const schema = HCS20_SCHEMAS[op];
    if (!schema) continue;
    sections.push(tableForSchema(op, schema));
  }

  return sections.join('\n');
}

function injectIntoDoc(existing: string, autogen: string): string {
  const startIdx = existing.indexOf(START_MARKER);
  const endIdx = existing.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1) {
    // No markers yet — append a new section at the bottom of the file.
    const trimmed = existing.replace(/\s+$/, '');
    return `${trimmed}\n\n---\n\n${START_MARKER}\n\n${autogen}\n${END_MARKER}\n`;
  }
  const before = existing.slice(0, startIdx + START_MARKER.length);
  const after = existing.slice(endIdx);
  return `${before}\n\n${autogen}\n${after}`;
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const existing = readFileSync(DOC_PATH, 'utf-8');
  const autogen = generateAutogen();
  const next = injectIntoDoc(existing, autogen);
  if (checkOnly) {
    if (next !== existing) {
      console.error(
        `[generate-schema-docs] ${DOC_PATH} is OUT OF DATE.\n` +
          `Run \`npm run schema:docs\` to regenerate.`,
      );
      process.exit(1);
    }
    console.log(`[generate-schema-docs] ${DOC_PATH} is up to date.`);
    return;
  }
  if (next === existing) {
    console.log(`[generate-schema-docs] ${DOC_PATH} already up to date.`);
    return;
  }
  writeFileSync(DOC_PATH, next, 'utf-8');
  console.log(`[generate-schema-docs] ${DOC_PATH} regenerated.`);
}

main();
